---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml
  # C for Celcius, F for Fahrenheit
  temperature_unit: C

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password

# Configure a default setup of Home Assistant (frontend, api, etc)
frontend:
  extra_html_url:
    - /local/icons/fontawesome/hass-fontawesome-solid.html
    - /local/icons/fontawesome/hass-fontawesome-regular.html
    - /local/icons/fontawesome/hass-fontawesome-brands.html
  javascript_version: latest

default_config:

# Updater
updater:

# Recorder
recorder: !include recorder.yaml

# Logger
logger: !include logger.yaml

# History
history: !include history.yaml

# Logbook
logbook: !include logbook.yaml

# Panel iFrame
panel_iframe: !include panel_iframe.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 8123
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.21.0.2      # Traefik container IP
    - 127.19.0.2      # Traefik container IP
    - 127.18.0.6      # node-red container IP
    - 192.168.1.0/24  # Local network
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Discover some devices automatically
discovery:
  ignore:
#    - homekit
    - apple_tv
    - belkin_wemo
    - bluesound
    - bose_soundtouch
    - enigma2
    - frontier_silicon
    - harmony
#    - igd
    - logitech_mediaserver
    - netgear_router
    - octoprint
    - openhome
#    - panasonic_viera
    - philips_hue
#    - roku
    - sabnzbd
    - samsung_printer
    - sonos
    - songpal
    - tellstick
    - wink
    - yamaha
#    - yeelight

# Zones
zone: !include zones.yaml

# Switches
switch: !include switches.yaml

# Media Players
media_player: !include media_player.yaml

# Sensors
sensor: !include_dir_merge_list sensors/

# Binary Sensors
binary_sensor: !include binary_sensor.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
timer: !include timer.yaml

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include GOOGLE_SERVICE_ACCOUNT.json
  #api_key: !secret google_assistant_api_key
  report_state: true
  exposed_domains:
    - switch
    - input_boolean
    # - light
    # - cover
    # - media_player
    # - group
    # - script

google_keep:
  username: !secret google_username
  password: !secret google_password
  list_name: "Grocery list"

# If this then that
ifttt:
  key: !secret ifttt_api

# Shelly.cloud
# https://github.com/StyraHem/ShellyForHASS
shelly:
  discovery: true
  version: true
  sensors:
    - all
  cloud_auth_key: !secret shelly_cloud_auth_key
  cloud_server: shelly-5-eu.shelly.cloud

# SmartIR
# https://github.com/smartHomeHub/SmartIR
smartir:

climate: !include climate.yaml

# REPLACED BY HACS
# https://custom-components.github.io/custom_updater/Installation
#custom_updater:
#  track:
#    - cards
#    - components
#    - python_scripts

### https://custom-components.github.io/hacs
hacs:
  token: !secret github_token
  sidepanel_title: "HACS"
  # python_script: true
  # theme: true
  options:
    experimental: true
    country: 'IL'

### https://github.com/Armaell/home-assistant-custom-icons-loader
custom_icons:

# https://github.com/Sanderhuisman/home-assistant-custom-components#docker_monitor
# SEEMS BROKEN
# docker_monitor:

# https://github.com/ualex73/monitor_docker
monitor_docker:
  - name: Docker
    rename:
      mariadb: MariaDB
      hass: Home Assistant
      mosquitto: Mosquitto
      node-red: "Node-RED"
      traefik: Traefik
      oauth: OAuth

# Xiomi Gateway
xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key
      host: 192.168.1.193

### Yeelight
yeelight:
  devices:
    192.168.1.198:
      name: Peninsula light
    192.168.1.96:
      name: Office light
    192.168.1.42:
      name: Storage light
    192.168.1.33:
      name: Cabinet light
    192.168.1.77:
      name: Curtain light
      model: strip1
    192.168.1.16:
      name: Stove light

# Device Tracker
device_tracker: !include device_tracker.yaml

# Input Boolean
input_boolean: !include input_boolean.yaml

# Input Text
input_text: !include input_text.yaml

# Input Select
input_select: !include input_select.yaml

# MQTT Broker
#mqtt:
#  broker: 127.0.0.1
#  client_id: home-assistant
#  keepalive: 60

#
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Scenes:
scene: !include scene.yaml


# HEOS
# heos:
#   host: 192.168.1.3

# System Health
system_health:

# Speed tests
speedtestdotnet:
  scan_interval:
    minutes: 30

# Tuya Smart Life
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_cc
  platform: smart_life

# Switcher
switcher_kis:
  phone_id: "0000"
  device_id: "bc005f"
  device_password: "00000000"

# Plants
plant: !include plants.yaml

jewish_calendar:

wake_on_lan:

webostv:
  host: 192.168.1.2
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "38:8C:50:82:51:F5"
#  customize:
#    sources:
#      - Marantz receiver
#      - Chromecast
#      - Netflix
#      - YouTube
#      - makoTV

# Notifications (require HTTPS)
notify:
  - platform: html5
    name: notify_html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

  #- platform: webostv
  #  host: 192.168.1.2
  #  name: lg_tv
  #  filename: webostv.conf

  - platform: pushbullet
    name: notify_pushbullet
    api_key: !secret pushbullet_token
