---
- platform: denonavr
  host: 192.168.1.3
  name: Marantz Reciever
  show_all_sources: true

- platform: webostv
  host: 192.168.1.2
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "38:8C:50:82:51:F5"

- platform: samsungtv
  host: 192.168.1.97
  name: Samsung TV
