---
# https://home-assistant.io/components/switch/

####################################################
#                                                  #
#             BROADLINK IR SWITCHES                #
#                                                  #
####################################################

# https://home-assistant.io/components/switch.broadlink/
- platform: broadlink
  host: 192.168.1.15
  mac: 34:EA:34:42:D7:58
  type: rm2_pro_plus
  switches:
    # Will work on most LG TVs
    tv_lg:
      friendly_name: "LG TV Power"
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
    tv_lg_hdmi1:
      friendly_name: "LG TV HDMI1"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG TV HDMI1 HDMI2"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
    tv_lg_hdmi2_hdmi3:
      friendly_name: "LG TV Chromecast/Marantz"
      command_on: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
      command_off: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
    tv_lg_hdmi3:
      friendly_name: "LG TV HDMI3"
      command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
    #tv_lg_av1_av2:
    #  friendly_name: "LG TV AV12"
    #  command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
    #  command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='
    ## Learned from Broadlink Manager
    tv_box_mute:
      friendly_name: "TV Box Mute"
      command_on: 'JgBgAAABJ5MTExMSEjgTEhMSExITEhMSFDcTNxMSEjgUNhQ2FDcSOBI4ExITEhM3EhMTExITEhMTEhI4FDYUERM3FDcTNxM3EwAFFQABJ0oTAAxUAAEnShIADFUAASZKFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABJ5MTExMSEjgTEhMSExITEhMSFDcTNxMSEjgUNhQ2FDcSOBI4ExITEhM3EhMTExITEhMTEhI4FDYUERM3FDcTNxM3EwAFFQABJ0oTAAxUAAEnShIADFUAASZKFAANBQAAAAAAAAAA'
    tv_box_ok:
      friendly_name: "TV Box OK"
      command_on: 'JgBYAAABKJEUERUQFBEUERQ3EzUVERIRFREUERQRExETOBM1FBIPFhIRFRAUNhMSEzcTERQRExEUNhQ2FRAUNRUREjYUNhQ2FAAFrgABKkcVAAxKAAEpSBMADQU='
      command_off: 'JgBYAAABKJEUERUQFBEUERQ3EzUVERIRFREUERQRExETOBM1FBIPFhIRFRAUNhMSEzcTERQRExEUNhQ2FRAUNRUREjYUNhQ2FAAFrgABKkcVAAxKAAEpSBMADQU='
    tv_box_channel_plus_minus:
      friendly_name: "TV Box Channel +/-"
      command_on: 'JgCQAAABJ5QTExEUERQRFRE5ETkRFBEUERQPFRIUERQRORE5ERURExIVEBQSFBA5EBUTExAUERURORI4EjgRFBI5EjgROBM4EQAFqwABJpYQFREUERQRFBE5EjkQFREUERQRFBEUEBUTNxQ2ERUQFRAWERMRFBI4EhISFRAUERQROhA6ETkRFBE5EToQORI4EwANBQAAAAAAAAAA'
      command_off: 'JgCQAAABJZUSExMWDxMSFBA6ETgSExIUERQSExEUEhMROhA5EhQSExE5ERQSExE6EBUQFRITEBURFBI3EzgRFRE4EToSOBA6EAAFrAABJpYSExISEBcREhI6EDoRFBEUEBURFBEUEhISOBI6EBUQFRE5ERMTExE5EBYRFBETERURExI4EzgRFBE5EToQORI5EQANBQAAAAAAAAAA'
    tv_box_up_down:
      friendly_name: "TV Box Up/Down"
      command_on: 'JgBYAAABJZYQFRETEhQQFRI4EjgRFREUEBUQFRAWEBQSOBA5ERURFRA6EBURExITEjkRFBITERQRFRA5EzgROhESEjgSORI5EgAFqgABJksSAAxVAAElTBIADQU='
      command_off: 'JgBQAAABKJAVEBURFBAUEBU1FDUVERQQFBAVEBcQFBAVNBU2Fg8VDxQ1Fg8VEBYQEzcTEBUQFRAVDxQ1FjUUNRURFDUWNRM1FQAFrwABKUYVAA0FAAAAAAAAAAA='
    tv_box_right_left:
      friendly_name: "TV Box Right/Left"
      command_on: 'JgBQAAABKZEUERUPEhIWDxY0FTUTEhEUFQ8VERUPFRAUNhQ2FRAUEBQ2FDUUEBQSFDUUExMRFBAVERMRFDcTNRURFTUTNRY0FgAFqwABKkkVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKpESEhYOFhAUERQ2FTMUEhMSFBAUEBQTExAVNRQ0FhEUEBUQFDUWDxUQFjUSEhMRFRAWNBQRFTQVNRUPFjUUNhM0FgAFrwABKEgUAA0FAAAAAAAAAAA='
    tv_box_1:
      friendly_name: "TV Box 1"
      command_on: 'JgBQAAABKJIUEBUQFBIUERM2FDYTERQRExMSERMSFBETNxM2FBITEhM2FQ8UEhI2FDgTEBITExEUExM1FDUVERITEzYVNRI4FAAFrwABJ0gVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKJIUEBUQFBIUERM2FDYTERQRExMSERMSFBETNxM2FBITEhM2FQ8UEhI2FDgTEBITExEUExM1FDUVERITEzYVNRI4FAAFrwABJ0gVAA0FAAAAAAAAAAA='
    tv_box_6:
      friendly_name: "TV Box 6"
      command_on: 'JgBYAAABJ5ETEhAWEhEUEhM3EzUVEBUQFRETEBQTExAUNhM3ExEWEBQREzYUNxM1FDYUEhMRFBISNhUQFBEUEBQSFDUSNxY1FAAFrgABKEkUAAxKAAEpSBQADQU='
      command_off: 'JgBYAAABJ5ETEhAWEhEUEhM3EzUVEBUQFRETEBQTExAUNhM3ExEWEBQREzYUNxM1FDYUEhMRFBISNhUQFBEUEBQSFDUSNxY1FAAFrgABKEkUAAxKAAEpSBQADQU='

# - platform: hadockermon
#   host: 127.0.0.1
#   port: 8126

# - platform: command_line
#   switches:
#     pihole_temp_disable:
#       command_on: "curl -X GET 'http://localhost/admin/api.php?disable=300&auth=YOUR-PIHOLE_API"
#       command_off: "curl -X GET 'http://localhost/admin/api.php?enable&auth=YOUR-PIHOLE_API"
