---
# https://home-assistant.io/components/switch/

####################################################
#                                                  #
#             BROADLINK IR SWITCHES                #
#                                                  #
####################################################

# https://home-assistant.io/components/switch.broadlink/
- platform: broadlink
  host: 192.168.1.15
  mac: 34:EA:34:42:D7:58
  type: rm2_pro_plus
  switches:
    # Will work on most LG TVs
    tv_lg:
      friendly_name: "LG TV Power"
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG TV HDMI12"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
    tv_lg_hdmi3:
      friendly_name: "LG TV HDMI3"
      command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
    tv_lg_av1_av2:
      friendly_name: "LG TV AV12"
      command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
      command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='

- platform: hadockermon
  host: 127.0.0.1
  port: 8126

- platform: command_line
  switches:
    pihole_temp_disable:
      command_on: "curl -X GET 'http://localhost/admin/api.php?disable=300&auth=YOUR-PIHOLE_API"
      command_off: "curl -X GET 'http://localhost/admin/api.php?enable&auth=YOUR-PIHOLE_API"
