# --- switches.yaml ---
#
# This file defines switches using the Template platform. This is the modern method for
# creating switches that send commands via the Broadlink integration.
# This requires the main 'broadlink:' integration to be configured in your configuration.yaml.
# For momentary switches, the 'turn_off' action calls an empty script named 'script.do_nothing'.
#

- platform: template
  switches:
    ################################################
    #                   LG TV                      #
    ################################################
    tv_lg_power:
      friendly_name: "LG TV Power"
      value_template: "{{ 'unavailable' }}" # This switch is a toggle, its state is unknown.
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='

    tv_lg_hdmi1:
      friendly_name: "LG TV HDMI1"
      value_template: "{{ 'off' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      turn_off:
        service: script.do_nothing # Call the empty script to satisfy validation.

    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG TV HDMI1 HDMI2"
      value_template: "{{ 'unavailable' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='

    tv_lg_chromecast_marantz:
      friendly_name: "LG TV Chromecast/Marantz"
      value_template: "{{ 'unavailable' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='

    tv_lg_hdmi3:
      friendly_name: "LG TV HDMI3"
      value_template: "{{ 'off' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
      turn_off:
        service: script.do_nothing # Call the empty script to satisfy validation.

    ################################################
    #                 TV Box                       #
    ################################################
    tv_box_mute:
      friendly_name: "TV Box Mute"
      value_template: "{{ 'unavailable' }}" # Toggle switch
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBgAAABJ5MTExMSEjgTEhMSExITEhMSFDcTNxMSEjgUNhQ2FDcSOBI4ExITEhM3EhMTExITEhMTEhI4FDYUERM3FDcTNxM3EwAFFQABJ0oTAAxUAAEnShIADFUAASZKFAANBQAAAAAAAAAA'
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBgAAABJ5MTExMSEjgTEhMSExITEhMSFDcTNxMSEjgUNhQ2FDcSOBI4ExITEhM3EhMTExITEhMTEhI4FDYUERM3FDcTNxM3EwAFFQABJ0oTAAxUAAEnShIADFUAASZKFAANBQAAAAAAAAAA'

    tv_box_ok:
      friendly_name: "TV Box OK"
      value_template: "{{ 'off' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBYAAABKJEUERUQFBEUERQ3EzUVERIRFREUERQRExETOBM1FBIPFhIRFRAUNhMSEzcTERQRExEUNhQ2FRAUNRUREjYUNhQ2FAAFrgABKkcVAAxKAAEpSBMADQU='
      turn_off:
        service: script.do_nothing # Call the empty script to satisfy validation.

    tv_box_channel_plus_minus:
      friendly_name: "TV Box Channel +/-"
      value_template: "{{ 'unavailable' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgCQAAABJ5QTExEUERQRFRE5ETkRFBEUERQPFRIUERQRORE5ERURExIVEBQSFBA5EBUTExAUERURORI4EjgRFBI5EjgROBM4EQAFqwABJpYQFREUERQRFBE5EjkQFREUERQRFBEUEBUTNxQ2ERUQFRAWERMRFBI4EhISFRAUERQROhA6ETkRFBE5EToQORI4EwANBQAAAAAAAAAA'
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgCQAAABJZUSExMWDxMSFBA6ETgSExIUERQSExEUEhMROhA5EhQSExE5ERQSExE6EBUQFRITEBURFBI3EzgRFRE4EToSOBA6EAAFrAABJpYSExISEBcREhI6EDoRFBEUEBURFBEUEhISOBI6EBUQFRE5ERMTExE5EBYRFBETERURExI4EzgRFBE5EToQORI5EQANBQAAAAAAAAAA'

    tv_box_up_down:
      friendly_name: "TV Box Up/Down"
      value_template: "{{ 'unavailable' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBYAAABJZYQFRETEhQQFRI4EjgRFREUEBUQFRAWEBQSOBA5ERURFRA6EBURExITEjkRFBITERQRFRA5EzgROhESEjgSORI5EgAFqgABJksSAAxVAAElTBIADQU='
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABKJAVEBURFBAUEBU1FDUVERQQFBAVEBcQFBAVNBU2Fg8VDxQ1Fg8VEBYQEzcTEBUQFRAVDxQ1FjUUNRURFDUWNRM1FQAFrwABKUYVAA0FAAAAAAAAAAA='

    tv_box_right_left:
      friendly_name: "TV Box Right/Left"
      value_template: "{{ 'unavailable' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABKZEUERUPEhIWDxY0FTUTEhEUFQ8VERUPFRAUNhQ2FRAUEBQ2FDUUEBQSFDUUExMRFBAVERMRFDcTNRURFTUTNRY0FgAFqwABKkkVAA0FAAAAAAAAAAA='
      turn_off:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABKpESEhYOFhAUERQ2FTMUEhMSFBAUEBQTExAVNRQ0FhEUEBUQFDUWDxUQFjUSEhMRFRAWNBQRFTQVNRUPFjUUNhM0FgAFrwABKEgUAA0FAAAAAAAAAAA='

    tv_box_1:
      friendly_name: "TV Box 1"
      value_template: "{{ 'off' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBQAAABKJIUEBUQFBIUERM2FDYTERQRExMSERMSFBETNxM2FBITEhM2FQ8UEhI2FDgTEBITExEUExM1FDUVERITEzYVNRI4FAAFrwABJ0gVAA0FAAAAAAAAAAA='
      turn_off:
        service: script.do_nothing # Call the empty script to satisfy validation.

    tv_box_6:
      friendly_name: "TV Box 6"
      value_template: "{{ 'off' }}"
      turn_on:
        service: broadlink.send
        data:
          host: 192.168.1.15
          packet: 'JgBYAAABJ5ETEhAWEhEUEhM3EzUVEBUQFRETEBQTExAUNhM3ExEWEBQREzYUNxM1FDYUEhMRFBISNhUQFBEUEBQSFDUSNxY1FAAFrgABKEkUAAxKAAEpSBQADQU='
      turn_off:
        service: script.do_nothing # Call the empty script to satisfy validation.
