calc_passwd:
  name: Calculate passwd
  description: Calculate default passwd.
  target:
    device:
      integration: miwifi

request:
  name: Send request
  description: Send request to router.
  target:
    device:
      integration: miwifi
  fields:
    uri:
      name: Uri
      description: Request uri.
      required: true
      example: "misystem/led"
      selector:
        text:
    body:
      name: Body
      description: Request body.
      required: false
      example: |
        on: 1
      selector:
        object:
          
block_device:
  name: "Block Device"
  description: "Enable or disable WAN access for a connected device (MiWiFi Router)."
  fields:
    device_id:
      name: Device
      description: "Select the device you want to block or unblock from internet access."
      required: true
      selector:
        device:
          integration: miwifi
          entity:
            domain: device_tracker
    allow:
      name: Allow Internet Access
      description: "Select 'On' to allow WAN access, or 'Off' to block WAN access for the selected device."
      required: true
      selector:
        boolean:
