---

########################################################################
### @link: https://www.home-assistant.io/components/jewish_calendar/ ###
########################################################################
- platform: jewish_calendar
  language: english
  sensors:
    - holiday_name
    - holyness
