---

##########################################################
### @url: https://home-assistant.io/components/sensor/ ###
### Setting template sensors of lights for floorplan   ###
##########################################################

## Master Bedroom ##
- platform: template
  sensors:
    master_bedroom_lights:
      entity_id: 
       - light.master_bedroom_hall_light
       - light.DUMMY_master_bedroom_main_light
      value_template: >-
        {% if is_state('light.master_bedroom_hall_light', 'on') and
          is_state('light.DUMMY_master_bedroom_main_light', 'on') %}
          All On
        {% elif is_state('light.master_bedroom_hall_light', 'off') and
          is_state('light.DUMMY_master_bedroom_main_light', 'off') %}
          All Off
        {% elif is_state('light.master_bedroom_hall_light', 'on') %}
          Hall On
        {% elif is_state('light.DUMMY_master_bedroom_main_light', 'on') %}
          Main On
        {% else %}
          Unknown
        {% endif %}

## Bathroom ##
- platform: template
  sensors:
    bathroom_lights:
      entity_id: 
       - light.DUMMY_bath_mirror_light
       - light.DUMMY_bath_wall_light
       - light.DUMMY_bath_recess_light
      value_template: >-
        {% if is_state('light.DUMMY_bath_mirror_light', 'on') and
          is_state('light.DUMMY_bath_wall_light', 'on') and
          is_state('light.DUMMY_bath_recess_light', 'on') %}
          All On
        {% elif is_state('light.DUMMY_bath_mirror_light', 'off') and
          is_state('light.DUMMY_bath_wall_light', 'off') and
          is_state('light.DUMMY_bath_recess_light', 'off') %}
          All Off
        # Unlikely combination - recess and wall  are connected
        {% elif is_state('light.DUMMY_bath_mirror_light', 'on') and
          is_state('light.DUMMY_bath_wall_light', 'on') %}
          Mirror and Wall On
        {% elif is_state('light.DUMMY_bath_recess_light', 'on') and
          is_state('light.DUMMY_bath_wall_light', 'on') %}
          Recess and Wall On
        # Unlikely combination - recess and wall  are connected
        {% elif is_state('light.DUMMY_bath_recess_light', 'on') and
          is_state('light.DUMMY_bath_mirror_light', 'on') %}
          Recess and Mirror On
        {% elif is_state('light.DUMMY_bath_mirror_light', 'on') %}
          Mirror On
        # Unlikely combination - recess and wall are connected
        {% elif is_state('light.DUMMY_bath_recess_light', 'on') %}
          Recess On
        # Unlikely combination - recess and wall are connected
        {% elif is_state('light.DUMMY_bath_wall_light', 'on') %}
          Wall On
        {% else %}
          Unknown
        {% endif %}

## Shower ##
- platform: template
  sensors:
    shower_lights:
      entity_id: 
       - light.DUMMY_shower_mirror_light
       - light.DUMMY_shower_wall_light
       - light.DUMMY_shower_main_light
      value_template: >-
        {% if is_state('light.DUMMY_shower_mirror_light', 'on') and
          is_state('light.DUMMY_shower_wall_light', 'on') and
          is_state('light.DUMMY_shower_main_light', 'on') %}
          All On
        {% elif is_state('light.DUMMY_shower_mirror_light', 'off') and
          is_state('light.DUMMY_shower_wall_light', 'off') and
          is_state('light.DUMMY_shower_main_light', 'off') %}
          All Off
        {% elif is_state('light.DUMMY_shower_mirror_light', 'on') and
          is_state('light.DUMMY_shower_wall_light', 'on') %}
          Mirror and Wall On
        {% elif is_state('light.DUMMY_shower_main_light', 'on') and
          is_state('light.DUMMY_shower_wall_light', 'on') %}
          Main and Wall On
        # Unlikely combination - wall and mirror are connected
        {% elif is_state('light.DUMMY_shower_main_light', 'on') and
          is_state('light.DUMMY_shower_mirror_light', 'on') %}
          Main and Mirror On
        # Unlikely combination - wall and mirror are connected
        {% elif is_state('light.DUMMY_shower_mirror_light', 'on') %}
          Mirror On
        {% elif is_state('light.DUMMY_shower_main_light', 'on') %}
          Main On
        # Unlikely combination - main and mirror are connected
        {% elif is_state('light.DUMMY_shower_wall_light', 'on') %}
          Wall On
        {% else %}
          Unknown
        {% endif %}

### Living room ###
- platform: template
  sensors:
    living_room_lights:
      entity_id:
        - light.cabinet_light
        - light.stove_light
        - light.peninsula_light
        - light.curtain_light
        - light.entry_light
        - light.balcony_light
      value_template: >
        {% set lights = ["cabinet_light",
                  "stove_light",
                  "peninsula_light",
                  "curtain_light",
                  "entry_light",
                  "balcony_light"]
        %}
        {% for state in states.light|sort(attribute='name') -%}
          {% if is_state(state.entity_id,"on") -%} 
            {{ state.name | regex_replace('(Kitchen )?(.*)[Ll]ight', '\\2') | title if (state.entity_id.replace("light.","") 
              in lights) else '' -}}
          {% endif -%}
        {% endfor -%} 