---
#https://home-assistant.io/components/sensor/

####################################################
#                                                  #
#                      MiFlora                     #
#                                                  #
####################################################

# Mi Flora
- platform: miflora
  mac: 'C4:7C:8D:65:BC:99'
  name: 'Crassula ovata (Jade plant)'
  force_update: false
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:6A:49:D5'
  name: 'Basil'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

# - platform: miflora
#  mac: 'C4:7C:8D:65:C1:D5'
#  name: 'Avocado'
#  force_update: false
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery

- platform: miflora
  mac: 'C4:7C:8D:67:14:FF'
  name: 'Ananas'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:C1:E6'
  name: 'Portulacaria afra'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:C1:DD'
  name: 'Anthurium'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:6A:64:C4'
  name: 'Peppermint'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:6A:68:CC'
  name: 'Kalanchoe Poseidon Pink'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:BC:99'
  name: 'Jade plant'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:6A:BB:CB'
  name: 'Sweet Alyssum'
  force_update: true
  scan_interval:
    minutes: 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
