---
#########################################################
###                       Pi-Hole                     ###
### https://www.home-assistant.io/components/pi_hole/ ###
#########################################################

- platform: pi-hole
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - domains_being_blocked
    - clients_ever_seen
