---
############################################################
### https://www.home-assistant.io/components/pushbullet/ ###
############################################################

- platform: pushbullet
  api_key: !secret pushbullet_token
