#https://home-assistant.io/components/sensor/

####################################################
#                                                  #
#                 WEATHER                          #
#                                                  #
####################################################

# - platform: yr
#   name: Weather
#   monitored_conditions:
#     - temperature
#     - symbol
#     - precipitation

# Template Sensor for Sun Angle
- platform: template
  sensors:
    solar_angle:
      friendly_name: "Sun Angle"
      unit_of_measurement: '°'
      value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"

# Pirate Weather Integration (replaces Dark Sky)
# - platform: pirateweather
#   api_key: !secret pirate_weather_api_key
#   latitude: !secret home_latitude
#   longitude: !secret home_longitude
#   units: ca
#   monitored_conditions:
#     - icon
#     - summary
#     - humidity
#     - temperature
#     - temperature_high
#     - temperature_low
#     - wind_speed
#     - wind_bearing
#     - precip_probability
#     - precip_intensity
#     - pressure
#     - visibility
#     - apparent_temperature

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
